'use client';
import {useEffect,useState} from 'react';
import {ArrowRightLeft, Sparkles, MapPin, Star, X, LoaderCircle, Check, ChevronRight, Github, BriefcaseBusiness, Clock3, Video, BadgeCheck, Search, Plus, Menu} from 'lucide-react';

const people=[
{name:'林墨',role:'产品设计师',city:'上海',teach:'摄影',learn:'Python',score:96,avatar:'LM',bio:'白天做产品设计，周末背着相机扫街。喜欢把复杂的东西讲简单，也正在补齐自己的技术能力。',reason:['你擅长的 Python 正是 TA 想学习的','TA 擅长的摄影正是你的学习目标','双方均接受线上交流','周末时间高度重合']},
{name:'Mia',role:'英语教练',city:'杭州',teach:'英语口语',learn:'UI设计',score:91,avatar:'MI'},
{name:'Kevin',role:'独立音乐人',city:'深圳',teach:'吉他',learn:'Python',score:89,avatar:'KV'},
{name:'Zoe',role:'视觉设计师',city:'北京',teach:'Figma',learn:'视频剪辑',score:87,avatar:'ZO'},
{name:'Jason',role:'健身教练',city:'广州',teach:'健身',learn:'英语',score:83,avatar:'JA'},
{name:'Emma',role:'内容创作者',city:'成都',teach:'视频剪辑',learn:'摄影',score:81,avatar:'EM'}];
const skills=['Python','摄影','吉他','英语口语','UI设计','健身','视频剪辑'];
const exchanges=[{name:'林墨',pair:'Python ⇄ 摄影',status:'进行中 · Week 2/4',progress:50},{name:'Mia',pair:'数据分析 ⇄ 英语口语',status:'等待确认',progress:10},{name:'Kevin',pair:'Python ⇄ 吉他',status:'已完成',progress:100}];
function Avatar({p,big=false}){return <div className="relative shrink-0"><div className={`${big?'w-20 h-20 text-xl':'w-12 h-12'} rounded-2xl bg-gradient-to-br from-violet-100 via-fuchsia-50 to-indigo-200 text-violet-700 grid place-items-center font-bold ring-1 ring-white shadow-sm`}>{p.avatar}</div><span className="absolute -right-0.5 -bottom-0.5 w-3.5 h-3.5 rounded-full bg-emerald-400 border-[3px] border-white" title="在线"/></div>}
function Modal({children,onClose,wide=false}){return <div className="fixed inset-0 z-50 bg-slate-950/25 backdrop-blur-sm p-4 grid place-items-center" onMouseDown={onClose}><div onMouseDown={e=>e.stopPropagation()} className={`fade card rounded-[28px] w-full ${wide?'max-w-3xl':'max-w-xl'} max-h-[90vh] overflow-auto p-6 md:p-8 relative`}><button onClick={onClose} className="absolute right-5 top-5 p-2 rounded-full hover:bg-slate-100"><X size={18}/></button>{children}</div></div>}
function MatchCard({p,onDetail,onSwap}){return <div className="match-card card rounded-[28px] p-5 md:p-6 transition duration-300"><div className="flex items-start justify-between gap-4"><div className="flex gap-3"><Avatar p={p}/><div><div className="flex items-center gap-2"><h3 className="font-semibold text-lg">{p.name}</h3><span className="text-[11px] text-emerald-600 font-semibold">● 在线</span></div><p className="text-sm text-slate-500">{p.role} · {p.city}</p><p className="mt-1 text-xs text-slate-400 flex items-center gap-1"><Star size={12} fill="currentColor" className="text-amber-400"/>4.9 · 已完成 18 次交换</p></div></div><div className="match-score"><div className="text-3xl font-black tracking-[-.05em] text-violet-600">{p.score}%</div><div className="text-[10px] font-bold uppercase tracking-[.2em] text-violet-400">Match</div></div></div><div className="swap-visual my-6"><div className="text-center"><p className="text-[10px] uppercase tracking-widest text-slate-400 mb-1">你教 TA</p><span className="skill-chip">{p.learn}</span></div><div className="swap-icon"><ArrowRightLeft size={20}/></div><div className="text-center"><p className="text-[10px] uppercase tracking-widest text-slate-400 mb-1">TA 教你</p><span className="skill-chip">{p.teach}</span></div></div>{p.reason?<div className="ai-panel mb-5"><p className="flex items-center gap-1.5 text-sm font-semibold mb-2 text-violet-800"><Sparkles size={15}/>AI 匹配理由</p>{p.reason.slice(0,2).map(r=><p key={r} className="text-sm text-slate-600 mt-1.5 flex gap-2"><Check size={14} className="mt-1 text-emerald-500 shrink-0"/>{r}</p>)}</div>:<div className="flex flex-wrap gap-2 mb-5"><span className="mini-tag">周末有空</span><span className="mini-tag">接受线上</span><span className="mini-tag">高信用</span></div>}<div className="flex gap-2"><button onClick={()=>onDetail(p)} className="btn flex-1 rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-semibold hover:bg-slate-50">查看详情</button><button onClick={()=>onSwap(p)} className="btn flex-1 rounded-xl bg-slate-950 text-white px-4 py-2.5 text-sm font-semibold hover:bg-violet-700">发起交换</button></div></div>}
export default function Page(){
const [tab,setTab]=useState('home'),[mobile,setMobile]=useState(false),[detail,setDetail]=useState(null),[swap,setSwap]=useState(null),[publish,setPublish]=useState(false),[ai,setAi]=useState(false),[plan,setPlan]=useState(false),[sent,setSent]=useState(false),[toast,setToast]=useState('');
useEffect(()=>{setSent(localStorage.getItem('skillswap_sent')==='1')},[]);
const notify=t=>{setToast(t);setTimeout(()=>setToast(''),2400)};
const generate=()=>{setAi(true);setTimeout(()=>{setAi(false);setPlan(true)},1400)};
const accept=()=>{localStorage.setItem('skillswap_sent','1');setSent(true);setSwap(null);notify('🎉 技能交换邀请已发送！')};
return <main className="min-h-screen"><header className="sticky top-0 z-40 glass border-b border-slate-100"><div className="max-w-6xl mx-auto h-16 px-5 flex items-center justify-between"><button onClick={()=>setTab('home')} className="flex items-center gap-2"><div className="w-9 h-9 rounded-xl bg-slate-950 text-white grid place-items-center"><ArrowRightLeft size={18}/></div><div className="text-left leading-tight"><b>SkillSwap</b><div className="text-[10px] text-slate-400">AI-powered Skill Exchange</div></div></button><nav className="hidden md:flex items-center gap-1 text-sm">{[['home','发现'],['match','我的匹配'],['exchange','交换记录']].map(([k,l])=><button key={k} onClick={()=>setTab(k)} className={`px-4 py-2 rounded-xl ${tab===k?'bg-slate-100 font-semibold':'text-slate-500 hover:text-slate-950'}`}>{l}</button>)}<button onClick={()=>notify('Alex · 产品经理｜Python / 数据分析')} className="ml-3 w-9 h-9 rounded-full bg-violet-100 text-violet-700 font-bold">A</button></nav><button onClick={()=>setMobile(!mobile)} className="md:hidden p-2 rounded-xl hover:bg-slate-100"><Menu/></button></div>{mobile&&<div className="md:hidden px-5 pb-4 bg-white/95 border-t border-slate-100 flex gap-2">{[['home','发现'],['match','我的匹配'],['exchange','交换记录']].map(([k,l])=><button key={k} onClick={()=>{setTab(k);setMobile(false)}} className="flex-1 py-2.5 text-sm rounded-xl bg-slate-50">{l}</button>)}</div>}</header>
{tab==='home'&&<><section className="hero max-w-6xl mx-auto px-5 pt-20 md:pt-28 pb-16 text-center"><div className="inline-flex items-center gap-2 pill rounded-full px-3 py-1.5 text-xs font-semibold mb-6"><Sparkles size={13}/>AI 驱动的技能互换社区</div><h1 className="hero-title text-5xl sm:text-6xl md:text-8xl font-black tracking-[-.065em] leading-[.98]">用你会的，<br/><span>换你想学的。</span></h1><p className="max-w-2xl mx-auto mt-6 text-slate-500 text-lg leading-8">每个人既可以是老师，也可以是学生。发布「我能教」和「我想学」，AI 帮你找到真正技能互补的人。</p><div className="mt-8 flex flex-col sm:flex-row justify-center gap-3"><button onClick={()=>setTab('match')} className="btn bg-slate-950 text-white rounded-2xl px-6 py-3.5 font-semibold hover:bg-violet-700 flex items-center justify-center gap-2"><Search size={18}/>寻找技能搭子</button><button onClick={()=>setPublish(true)} className="btn card rounded-2xl px-6 py-3.5 font-semibold flex items-center justify-center gap-2"><Plus size={18}/>发布我的技能</button></div><div className="hero-exchange mt-12 mx-auto"><div><small>你可以分享</small><b>Python</b></div><div className="hero-swap"><ArrowRightLeft size={22}/><span>AI 双向匹配</span></div><div><small>你可以学到</small><b>摄影</b></div></div><div className="mt-7 flex flex-wrap justify-center gap-2">{skills.map(s=><button key={s} onClick={()=>{setTab('match');notify(`正在寻找「${s}」技能搭子`)}} className="px-3 py-1.5 rounded-full bg-white border border-slate-200 text-sm text-slate-500 hover:border-violet-300 hover:text-violet-700 transition">{s}</button>)}</div></section><section className="max-w-6xl mx-auto px-5 pb-24"><div className="flex items-end justify-between mb-5"><div><p className="text-violet-600 text-sm font-semibold">FOR ALEX</p><h2 className="text-2xl md:text-3xl font-bold mt-1">今日最适合你的技能搭子</h2></div><button onClick={()=>setTab('match')} className="hidden sm:flex items-center text-sm font-semibold gap-1">查看全部 <ChevronRight size={16}/></button></div><div className="grid md:grid-cols-3 gap-4">{people.slice(0,3).map(p=><MatchCard key={p.name} p={p} onDetail={setDetail} onSwap={p=>{setSwap(p);setPlan(false)}}/>)}</div></section></>}
{tab==='match'&&<section className="max-w-6xl mx-auto px-5 py-14"><div className="mb-8"><div className="flex items-center gap-2 text-violet-600 text-sm font-semibold"><Sparkles size={16}/>AI SMART MATCH</div><h1 className="text-4xl font-bold mt-2">为你找到 12 位技能搭子</h1><p className="text-slate-500 mt-2">综合技能互补、时间和学习方式，为你优先推荐。</p></div><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">{people.map(p=><MatchCard key={p.name} p={p} onDetail={setDetail} onSwap={p=>{setSwap(p);setPlan(false)}}/>)}</div></section>}
{tab==='exchange'&&<section className="max-w-4xl mx-auto px-5 py-14"><p className="text-violet-600 text-sm font-semibold">MY EXCHANGES</p><h1 className="text-4xl font-bold mt-2 mb-8">我的技能交换</h1><div className="space-y-4">{exchanges.map((e,i)=><div key={e.name} className="card rounded-3xl p-6"><div className="flex justify-between items-center gap-4"><div><p className="text-sm text-slate-400">Alex ⇄ {e.name}</p><h3 className="text-xl font-bold mt-1">{e.pair}</h3></div><span className={`text-xs px-3 py-1.5 rounded-full ${i===0?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-600'}`}>{e.status}</span></div><div className="mt-5 h-2 bg-slate-100 rounded-full overflow-hidden"><div className="h-full bg-violet-500 rounded-full" style={{width:e.progress+'%'}}/></div></div>)}</div></section>}
{detail&&<Modal onClose={()=>setDetail(null)}><div className="flex gap-4 items-center"><Avatar p={detail} big/><div><h2 className="text-2xl font-bold">{detail.name}</h2><p className="text-slate-500 flex items-center gap-1 mt-1"><BriefcaseBusiness size={14}/>{detail.role} · <MapPin size={14}/>{detail.city}</p></div></div><p className="text-slate-500 leading-7 mt-6">{detail.bio||'热爱分享，也保持学习。希望通过技能交换认识有趣的人，并把每次学习都变成一次真实合作。'}</p><div className="grid grid-cols-2 gap-3 mt-6"><div className="rounded-2xl bg-violet-50 p-4"><p className="text-xs text-slate-400">我能教</p><b className="block mt-1">{detail.teach}</b></div><div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs text-slate-400">我想学</p><b className="block mt-1">{detail.learn}</b></div></div><div className="mt-7"><h3 className="font-bold">技能信用</h3><div className="flex items-center gap-2 mt-3"><span className="font-semibold">{detail.teach}</span><span className="text-amber-500 flex"><Star size={15} fill="currentColor"/> 4.9</span><span className="text-sm text-slate-400">18 人交换过</span></div><div className="flex flex-wrap gap-2 mt-3">{['耐心','讲解清晰','守时','适合零基础'].map(x=><span key={x} className="bg-slate-100 px-2.5 py-1 rounded-lg text-xs">{x}</span>)}</div></div><div className="mt-7"><h3 className="font-bold">Skill Proof</h3><div className="mt-3 grid sm:grid-cols-3 gap-2 text-sm"><div className="border rounded-xl p-3 flex gap-2"><Github size={17}/>GitHub 项目</div><div className="border rounded-xl p-3 flex gap-2"><BriefcaseBusiness size={17}/>个人作品集</div><div className="border rounded-xl p-3 flex gap-2"><BadgeCheck size={17}/>交换者认证 ×12</div></div></div><button onClick={()=>{setDetail(null);setSwap(detail);setPlan(false)}} className="btn mt-7 w-full bg-slate-950 text-white rounded-xl py-3 font-semibold">发起技能交换</button></Modal>}
{publish&&<Modal onClose={()=>setPublish(false)} wide><h2 className="text-2xl font-bold">发布我的技能</h2><p className="text-slate-500 mt-1">告诉社区你能分享什么，以及下一项想掌握的技能。</p><div className="grid md:grid-cols-2 gap-6 mt-7"><div><h3 className="font-bold mb-3">我能教</h3>{['技能名称：Python','技能水平：熟练','可以教授：Python 基础、Pandas 数据分析'].map(x=><div key={x} className="border rounded-xl px-4 py-3 text-sm mb-2 text-slate-600">{x}</div>)}<div className="flex gap-2"><span className="pill rounded-lg px-3 py-2 text-xs">线上</span><span className="border rounded-lg px-3 py-2 text-xs">线下</span></div></div><div><h3 className="font-bold mb-3">我想学</h3>{['技能名称：摄影','目标：4 周掌握人像摄影基础','当前水平：入门','每周投入：2 小时'].map(x=><div key={x} className="border rounded-xl px-4 py-3 text-sm mb-2 text-slate-600">{x}</div>)}</div></div><button onClick={()=>{setAi(true);setTimeout(()=>{setAi(false);notify('✨ AI 已将技能介绍优化得更清晰、更有吸引力')},1200)}} className="mt-6 w-full rounded-xl bg-violet-50 text-violet-700 py-3 font-semibold flex justify-center items-center gap-2">{ai?<LoaderCircle className="spin" size={18}/>:<Sparkles size={18}/>}AI 帮我完善技能介绍</button><button onClick={()=>{setPublish(false);notify('技能卡已发布，正在为你寻找匹配')} } className="mt-3 w-full rounded-xl bg-slate-950 text-white py-3 font-semibold">发布技能卡</button></Modal>}
{swap&&<Modal onClose={()=>setSwap(null)}><p className="text-violet-600 text-sm font-semibold">SKILL EXCHANGE</p><h2 className="text-2xl font-bold mt-1">和 {swap.name} 发起交换</h2><div className="mt-6 rounded-2xl bg-slate-50 p-5"><div className="flex items-center justify-between gap-3"><div><p className="text-xs text-slate-400">你提供</p><b>Python 数据分析</b></div><ArrowRightLeft className="text-violet-500"/><div className="text-right"><p className="text-xs text-slate-400">对方提供</p><b>{swap.teach==='摄影'?'人像摄影':swap.teach}</b></div></div></div><div className="grid grid-cols-2 gap-3 mt-3"><div className="border rounded-xl p-3 text-sm flex gap-2"><Video size={17}/>线上交换</div><div className="border rounded-xl p-3 text-sm flex gap-2"><Clock3 size={17}/>每周 2 小时</div></div>{!plan?<button onClick={generate} disabled={ai} className="mt-6 w-full rounded-xl bg-violet-600 text-white py-3 font-semibold flex justify-center items-center gap-2">{ai?<><LoaderCircle className="spin" size={18}/>AI 正在规划...</>:<><Sparkles size={18}/>AI 生成交换计划</>}</button>:<div className="fade mt-6"><div className="flex items-center gap-2"><Sparkles size={18} className="text-violet-500"/><h3 className="font-bold">4 周技能交换计划</h3></div><div className="mt-3 space-y-2">{[['Week 1','Python 基础与环境配置','相机参数与曝光三要素'],['Week 2','Pandas 数据处理','构图与光线'],['Week 3','数据可视化','人像摄影实战'],['Week 4','作品展示 + Feedback','作品展示 + Feedback']].map(w=><div key={w[0]} className="border rounded-xl p-3"><b className="text-sm">{w[0]}</b><p className="text-xs text-slate-500 mt-1">Alex → {swap.name}：{w[1]}</p><p className="text-xs text-slate-500">{swap.name} → Alex：{w[2]}</p></div>)}</div><div className="flex gap-2 mt-4"><button onClick={()=>setPlan(false)} className="flex-1 border rounded-xl py-3 font-semibold">调整计划</button><button onClick={accept} className="flex-1 bg-slate-950 text-white rounded-xl py-3 font-semibold">接受计划</button></div></div>}{sent&&!plan&&<p className="text-center mt-4 text-sm text-emerald-600">已发送过邀请 · 等待对方接受</p>}</Modal>}
{toast&&<div className="fixed bottom-6 left-1/2 -translate-x-1/2 z-[70] bg-slate-950 text-white px-5 py-3 rounded-2xl shadow-xl text-sm fade">{toast}</div>}</main>}
